### ISSUE TITLE
Problem About Dataset

### ISSUE THREAD

**Issue by 254788** [xchhuang/simple-pytorch-3dgan#1]
Hello, I am a student studying GAN. I cannot download the data set. Is it convenient for you to provide it?  Given that time has passed, it ’s okay if you ca n’t find it。thank you very much!

**Comment by SSITB** [comment]
Hi, you can download it from the below path, it's 500MB

http://3dshapenets.cs.princeton.edu/3DShapeNetsCode.zip

**Comment by xchhuang** [comment]
Hi @254788 , does it work with @SSITB 's link ? I remembered I also put it in the readme.
