### ISSUE TITLE
wired results 

### ISSUE THREAD

**Issue by xinwei-zhuang** [xchhuang/simple-pytorch-3dgan#4]
Hi! Thanks for your code, it's super pipeline complete. When I try to execute it and I didn't change anything, the results seems to be void. see the results after the 1st, 3rd and 5th epochs. Is this normal...?

![000](https://user-images.githubusercontent.com/39757009/150465954-755728d1-01a0-44f6-86c4-a881e200aa05.png)
![002](https://user-images.githubusercontent.com/39757009/150465958-cff2194a-7837-4d0c-899f-fcf1f6dd0063.png)
![005](https://user-images.githubusercontent.com/39757009/150465960-60101937-0c54-4dba-8138-9d58fae7440e.png)

**Comment by xchhuang** [comment]
Thanks for your interest. 

It seems normal to me, I started to see the chairs after more or less 20 epochs.

**Comment by xinwei-zhuang** [comment]
just to confirm that after ~300 epochs it gives reasonalbe results! many thanks. Can I ask which parameter I can use to continue my training after saving the model?

**Comment by xchhuang** [comment]
> just to confirm that after ~300 epochs it gives reasonalbe results! many thanks. Can I ask which parameter I can use to continue my training after saving the model?

Sorry for the late reply. I think you could simply add ```torch.load(the_path_of_your_saved_model)``` following https://pytorch.org/docs/stable/generated/torch.load.html somewhere in ```trainer.py``` before the training loop.
